server:
  port: 8080

spring:
#  redis:
#    host: 127.0.0.1
#    port: 6379
#    password: 123456
  datasource:
    password: 123456
    username: root
    url: jdbc:mysql://127.0.0.1:3306/video?characterEncoding=utf-8&serverTimezone=UTC
  jpa:
    hibernate:
      ddl-auto: update
  data:
    mongodb:
      uri: mongodb://exchange:123456@127.0.0.1:27017/exchange
